language: python
sudo: required
python:
  - "3.6"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python setup.py sdist upload
deploy:
  provider: pypi
  user: "konraditurbe"
  password:
    secure: "???"
